const {JSDOM,VirtualConsole}=require('jsdom');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const base=path.resolve(__dirname,'..'),errors=[];
const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(e.type!=='css-parsing')errors.push(e.message)});
const html=fs.readFileSync(path.join(base,'index.html'),'utf8').replace(/<script[^>]*src="([^"]+)"[^>]*><\/script>/g,(_,src)=>'<script>'+fs.readFileSync(path.join(base,src.split('?')[0]),'utf8').replace(/<\/script/gi,'<\\/script')+'</script>');
const dom=new JSDOM(html,{url:'https://pulse.test/Portfolio-Pulse/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.scrollTo=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});w.ResizeObserver=class{observe(){}disconnect(){}};w.HTMLElement.prototype.scrollIntoView=function(){}}});
const w=dom.window,delay=()=>new Promise(r=>setTimeout(r,180));
const click=t=>{const b=[...w.document.querySelectorAll('button')].find(x=>x.textContent.trim()===t);assert(b,`button ${t}`);b.click()};
const role=async value=>{const s=w.document.querySelector('.role-control select');s.value=value;s.dispatchEvent(new w.Event('change',{bubbles:true}));await delay()};
(async()=>{
 await new Promise(r=>w.addEventListener('load',r));await delay();
 const projects=w.PPSecretaryBridge.projects;
 assert(projects.every(p=>p.stages.every(s=>s.status!=='done'||s.actualEnd<=w.PPSecretaryBridge.date)));
 assert(projects.some(p=>p.stages.some(s=>s.status==='notStarted'&&s.forecastEnd>w.PPSecretaryBridge.date)));
 console.log('PASS historical demo has no completed future stage');
 click('Портфель');await delay();
 const amber=[...w.document.querySelectorAll('.data-table tbody tr')].find(x=>x.textContent.includes('Amber Coast Energy'));assert(amber);amber.click();await delay();
 const drawer=w.document.querySelector('.project-drawer');assert(drawer.textContent.includes('Ручной управленческий риск'));
 assert(drawer.textContent.includes('Подтвердить следующий результат'));
 console.log('PASS manual risk reason and Russian next action appear in CEO drawer');
 drawer.querySelector('.icon-button').click();
 await role('contracts');
 const rows=[...w.document.querySelectorAll('.data-table tbody tr')];
 assert(rows.length>0);
 assert(!rows.some(row=>row.textContent.includes('0 $ остаток')));
 console.log('PASS contract radar excludes fully paid milestones');
 await role('accountant');
 assert(w.document.querySelector('h1')?.textContent==='Дебиторка');
 assert(![...w.document.querySelectorAll('.side-nav button')].find(x=>x.textContent.trim()==='Платежи')?.classList.contains('active'));
 w.document.querySelector('.data-table tbody tr').click();await delay();
 const dialog=w.document.querySelector('[role="dialog"]'),amount=dialog.querySelector('input[type="number"]'),submit=dialog.querySelector('button[type="submit"]');
 assert.equal(amount.value,'');assert(submit.disabled);
 amount.value='9999999';amount.dispatchEvent(new w.Event('change',{bubbles:true}));await delay();assert(submit.disabled);
 console.log('PASS accounting amount requires explicit entry within outstanding balance');
 dialog.querySelector('footer button').click();
 await role('specialist');
 const shadow=w.document.querySelector('#pp-workforce-mount').shadowRoot;
 assert(shadow.textContent.includes('27 июл.')||shadow.textContent.includes('27 Jul'));
 console.log('PASS specialist starts in week of historical demo snapshot');
 assert.deepEqual(errors,[]);console.log('PASS no runtime errors');dom.window.close();
})().catch(e=>{console.error(e,errors);dom.window.close();process.exitCode=1});
