const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const base=path.resolve(__dirname,'..'),errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(e.type!=='css-parsing')errors.push(e.message)});
const html=fs.readFileSync(path.join(base,'index.html'),'utf8').replace(/<script[^>]*src="([^"]+)"[^>]*><\/script>/g,(_,src)=>'<script>'+fs.readFileSync(path.join(base,src.split('?')[0]),'utf8').replace(/<\/script/gi,'<\\/script')+'</script>');
const dom=new JSDOM(html,{url:'https://pulse.test/Portfolio-Pulse/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.scrollTo=()=>{};w.matchMedia=()=>({matches:false,addEventListener(){}});w.ResizeObserver=class{observe(){}disconnect(){}};w.HTMLElement.prototype.scrollIntoView=function(){};w.confirm=()=>true}});
const w=dom.window,wait=()=>new Promise(r=>setTimeout(r,70)),click=t=>{const b=[...w.document.querySelectorAll('button')].find(x=>x.textContent.trim()===t);assert(b,`button ${t}`);b.click()},choose=(el,v)=>{el.value=v;el.dispatchEvent(new w.Event('change',{bubbles:true}))};
(async()=>{await new Promise(r=>w.addEventListener('load',r));await wait();let bridge=()=>w.PPSecretaryBridge;
// Twelve new engagements, recurring names, a staffing transfer and one unpaid invoice.
const created=[];for(let m=0;m<12;m++){let month=(8+m-1)%12+1,year=2026+Math.floor((7+m)/12),start=`${year}-${String(month).padStart(2,'0')}-05`;let p=bridge().createDraft({client:`Year Client ${m%5}`,name:`Review ${m}`,country:m%2?'Oman':'Kazakhstan',start,amount:200000+m*10000});assert(bridge().commit(p.id,null,p));created.push(p.id);await wait()}
assert.equal(new Set(created).size,12);assert.equal(new Set(created.map(id=>bridge().projects.find(p=>p.id===id).code)).size,12);
// Renewing an identical engagement through the visible form must never overwrite the first one.
bridge().changePersona('coordinator','analyst-2');await wait();
for(let n=0;n<2;n++){click('Новый проект');await wait();const d=w.document.querySelector('[role="dialog"]'),input=label=>[...d.querySelectorAll('label')].find(x=>x.textContent.includes(label))?.querySelector('input,select');for(const [label,value] of [['Название проекта','Annual renewal'],['Клиент','Repeat Energy'],['Дата начала','2027-07-05']]){const el=input(label);assert(el);Object.getOwnPropertyDescriptor(w.HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new w.Event('input',{bubbles:true}));el.dispatchEvent(new w.Event('change',{bubbles:true}))}d.querySelector('button[type="submit"]').click();await wait()}
const renewals=bridge().projects.filter(p=>p.client==='Repeat Energy');assert.equal(renewals.length,2);assert.equal(new Set(renewals.map(p=>p.id)).size,2);assert.equal(new Set(renewals.map(p=>p.code)).size,2);
for(const id of created){const original=bridge().projects.find(p=>p.id===id),assigned=JSON.parse(JSON.stringify(original));assigned.stages[0].assignments.push({memberId:'analyst-2',linkedStageId:assigned.stages[0].id,startDate:assigned.stages[0].forecastStart,endDate:assigned.stages[0].forecastEnd,plannedDays:12,remainingDays:12,actualDays:0,load:40});assert(bridge().commit(id,JSON.stringify(original),assigned));await wait()}
const project=bridge().projects.find(p=>p.id===created[0]),billed=JSON.parse(JSON.stringify(project));billed.milestones[0].invoiceNo='YEAR-001';billed.milestones[0].invoiceDate='2026-08-20';billed.milestones[0].expectedReceiptDate='2026-09-20';billed.milestones[0].transactions=[{id:'receipt-year',type:'receipt',date:'2026-09-01',amount:20000,note:'Partial receipt'}];assert(bridge().commit(project.id,JSON.stringify(project),billed));await wait();
bridge().changePersona('ceo','analyst-6');await wait();const core=w.PPWorkforceCore,ctx=bridge(),actor={...core.profiles(ctx).find(m=>m.id==='analyst-2'),role:'specialist'},manager={...core.profiles(ctx).find(m=>m.id===ctx.projects.find(p=>p.id===created[0]).coordinatorId),role:'coordinator'},ledger=core.init(ctx);for(let k=0;k<52;k++){let week=core.add('2026-08-03',k*7),p=ctx.projects.find(x=>x.id===created[k%12]),entry={id:`annual-${k}`,memberId:actor.id,week,projectId:p.id,category:'billable',activity:'technical',days:[8,8,8,8,8,0,0],note:'Technical review',outputs:[],unit:'reservoir',status:'draft'};ledger.entries.push(entry);core.submit(ledger,[entry.id],ctx,actor,week+'T12:00:00Z');core.review(ledger,entry.id,'approved','',ctx,manager,week+'T13:00:00Z')}assert.equal(core.validateRows(ledger.entries),'');assert.equal(ledger.entries.reduce((s,e)=>s+core.hours(e),0),2080);assert(ledger.entries.every(e=>e.status==='approved'));w.localStorage.setItem('pp-workforce-v28',JSON.stringify(ledger));
// A coordinator with no project must not inherit unrelated clients.
const unassigned=bridge().team.find(m=>!bridge().projects.some(p=>!p.archived&&p.coordinatorId===m.id));assert(unassigned);bridge().changePersona('coordinator',unassigned.id);await wait();bridge().navigate('portfolio');await wait();assert(!w.document.querySelector('main').textContent.includes('Year Client 0'));
// A lost contract retains its actual receipts and billed debt in finance.
bridge().changePersona('ceo','analyst-6');await wait();bridge().navigate('portfolio');await wait();bridge().open(created[0]);await wait();const target=[...w.document.querySelectorAll('.data-table tbody tr')].find(x=>x.textContent.includes('Year Client 0'));assert(target);target.querySelector('.project-menu button').click();await wait();const dlg=w.document.querySelector('.archive-reason-fields')?.closest('[role="dialog"]');assert(dlg);const outcome=dlg.querySelector('.archive-reason-fields select'),reason=dlg.querySelector('.archive-reason-fields textarea');choose(outcome,'lost');Object.getOwnPropertyDescriptor(w.HTMLTextAreaElement.prototype,'value').set.call(reason,'Client canceled after partial delivery');reason.dispatchEvent(new w.Event('input',{bubbles:true}));reason.dispatchEvent(new w.Event('change',{bubbles:true}));await wait();assert(!dlg.querySelector('.danger-button').disabled);dlg.querySelector('.danger-button').click();await wait();const archived=bridge().projects.find(p=>p.id===created[0]);assert.equal(archived.archiveOutcome,'lost');assert.equal(archived.archiveReason,'Client canceled after partial delivery');bridge().navigate('receivables');await wait();assert(w.document.querySelector('main').textContent.includes('Year Client 0'));bridge().navigate('overview');await wait();const actual=()=>[...w.document.querySelectorAll('article')].find(x=>x.textContent.includes('Факт из плана на дату'))?.querySelector('strong')?.textContent;const before=actual();assert(before);bridge().navigate('portfolio');await wait();const seeded=bridge().projects.find(p=>!p.archived&&p.milestones.some(m=>m.transactions.some(t=>t.date<='2026-07-31')));assert(seeded);const seededRow=[...w.document.querySelectorAll('.data-table tbody tr')].find(x=>x.textContent.includes(seeded.code));assert(seededRow);seededRow.querySelector('.project-menu button').click();await wait();const seededDialog=w.document.querySelector('.archive-reason-fields').closest('[role="dialog"]');const seededReason=seededDialog.querySelector('textarea');Object.getOwnPropertyDescriptor(w.HTMLTextAreaElement.prototype,'value').set.call(seededReason,'Completed after payment');seededReason.dispatchEvent(new w.Event('input',{bubbles:true}));await wait();seededDialog.querySelector('.danger-button').click();await wait();bridge().navigate('overview');await wait();assert.equal(actual(),before);assert.equal(bridge().projects.find(p=>p.id===seeded.id).archiveOutcome,'completed');
// Prior approved work is retained, while a new draft on a lost contract cannot be submitted.
const lostCtx=bridge(),lostLedger=core.init(lostCtx),oldEntry=ledger.entries[0];assert.equal(oldEntry.status,'approved');const forbidden={...oldEntry,id:'after-loss',week:'2027-08-02',status:'draft',days:[2,0,0,0,0,0,0]};lostLedger.entries.push(forbidden);assert.throws(()=>core.submit(lostLedger,[forbidden.id],lostCtx,actor,'2027-08-04T00:00:00Z'),/permission/);
// A division manager must not inherit another division's archived receivables.
const outside=bridge().projects.find(p=>p.division==='americas'&&!p.archived);assert(outside);const outsidePaid=JSON.parse(JSON.stringify(outside));outsidePaid.milestones[0].invoiceNo='FOREIGN-001';outsidePaid.milestones[0].invoiceDate='2026-07-01';outsidePaid.milestones[0].expectedReceiptDate='2026-07-20';assert(bridge().commit(outside.id,JSON.stringify(outside),outsidePaid));await wait();bridge().navigate('portfolio');await wait();const foreignRow=[...w.document.querySelectorAll('.data-table tbody tr')].find(x=>x.textContent.includes(outside.code));assert(foreignRow);foreignRow.querySelector('.project-menu button').click();await wait();const foreignDialog=w.document.querySelector('.archive-reason-fields').closest('[role="dialog"]');const foreignReason=foreignDialog.querySelector('textarea');Object.getOwnPropertyDescriptor(w.HTMLTextAreaElement.prototype,'value').set.call(foreignReason,'Americas contract closed');foreignReason.dispatchEvent(new w.Event('input',{bubbles:true}));await wait();foreignDialog.querySelector('.danger-button').click();await wait();
bridge().changePersona('division','analyst-1');await wait();bridge().navigate('receivables');await wait();assert(!w.document.querySelector('main').textContent.includes('FOREIGN-001'));
// Reset clears the entire demo dataset, including the 52-week ledger.
click('Сбросить демо');await wait();assert.equal(bridge().projects.length,30);assert.equal(JSON.parse(w.localStorage.getItem('pp-workforce-v28')).entries.length,0);
assert.deepEqual(errors,[]);console.log('PASS 12 projects across 12 months, assignment, billing, 52 weeks and scoped access');dom.window.close();})().catch(e=>{console.error(e,errors);dom.window.close();process.exitCode=1});
